# Generated by Django 4.2.4 on 2023-09-01 05:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس ایمیل')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='تلفن همراه')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='نام کامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='اکتیو بودن کاربر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین بودن کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
