# Generated by Django 4.2.4 on 2023-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'پیامک ارسالی', 'verbose_name_plural': 'پیامک های ارسالی'},
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
    ]
