# Generated by Django 4.2.4 on 2023-09-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_expration_date_otp_expration_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expration_date_start',
            new_name='expration_date',
        ),
    ]
