# Generated by Django 4.1.6 on 2023-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_otp_expration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
